### ISSUE TITLE
Running ./schemer.py fails

### ISSUE THREAD

**Issue by PQCraft** [jonocodes/GtkSourceSchemer#2]
```
/home/pqcraft/Documents/GtkSourceSchemer/./schemer.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GdkPixbuf, Gdk, GtkSource
/home/pqcraft/Documents/GtkSourceSchemer/./schemer.py:27: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '5') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GdkPixbuf, Gdk, GtkSource
Traceback (most recent call last):
  File "/home/pqcraft/Documents/GtkSourceSchemer/./schemer.py", line 688, in <module>
    sys.exit(main())
  File "/home/pqcraft/Documents/GtkSourceSchemer/./schemer.py", line 684, in main
    GUI(fromFile)
  File "/home/pqcraft/Documents/GtkSourceSchemer/./schemer.py", line 69, in __init__
    self.colorBlack = Gdk.color_parse('#000000');
  File "/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gdk' object has no attribute 'color_parse'
```

**Comment by PQCraft** [comment]
Here's a version I made a few "just get it working" patches to
[schemer.zip](https://github.com/jonocodes/GtkSourceSchemer/files/10789303/schemer.zip)
